name: 'issue-labeler'
description: 'Label issues and assign maintainer based on the issue content.'
author: 'ngc7331'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  BOT_GITHUB_TOKEN:
    description: 'The issue labeler bot GITHUB_TOKEN.'
    required: true
  CONFIG_PATH:
    description: 'The path to the configuration file.'
    required: true
    default: '.github/issue-labeler.yml'

# Define your outputs here.
# outputs:

runs:
  using: node20
  main: dist/index.js
